openapi: 3.0.1
info:
  title: Authorization Service
  description: This is a service that checks if incoming requests are authorized to access the api
  contact:
    email: support@bam.io
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: 1.0.0
tags:
- name: Authorization Service
  description: Auth Endpoint
  externalDocs:
    description: Find out more
    url: http://staging.chain-abstraction.dev
paths:
  /api/v1/health/status:
    get:
      tags:
      - Authorization Service
      summary: Check the health of the service
      operationId: healthCheck
      responses:
        200:
          description: healthy response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Health'
        404:
          description: Not found
          content: {}
        401:
          description: Unauthorized
          content: {}
      security:
      - auth:
        - bam:access
  /api/v1/auth/auth:
    get:
      tags:
      - Authorization Service
      summary: Checks if user is authenticated
      operationId: authCheck
      responses:
        200:
          description: User is authorized
        401:
          description: Unauthorized
          content: {}
        500:
          description: Internal Server Error
          content: {}
      security:
        - Auth: []
        - AuthId: []
components:
  schemas:
    Health:
      type: object
      properties:
        message:
          type: string
          example: Healthy response from service at - 2019-10-28 01:15:49.392631014 +0000 GMT m=+72.576498242
        statusCode:
          type: number
          example: 200
  securitySchemes:
    Auth:
      type: apiKey
      in: header
      name: Bam-Key
    AuthId:
      type: apiKey
      in: header
      name: Eth-Id